### ISSUE TITLE
Several test failures

### ISSUE THREAD

**Issue by crazycodr** [Dufgui/com.mds.lsp.tcl#1]
Hi,

I was interrested in this because we use vscode and TCL at work. Is this project under active development? There seems to be a few tests failing on the master branch:

```
Failed tests:   testCmd(tcl.lang.cmd.ApplyCmdTest): Expected-to-fail tcl test cases that were not reported as failed: [apply-8.4, apply-8.5, apply-8.6, apply-8.7, apply-8.8](..)
  testCmd(tcl.lang.cmd.UpvarCmdTest): Expected-to-fail tcl test cases that were not reported as failed: [upvar-3.5, upvar-3.6](..)
  testRegexSyntax(tcl.lang.cmd.RegexCmdTest): Expected-to-fail tcl test cases that were not reported as failed: [reg-14.9.execute](..)
  testCmd(tcl.lang.cmd.SocketCmdTest): Unexpected failed tcl test cases: [socket-2.9, socket-3.1]
  testCmd(tcl.lang.cmd.InfoCmdTest): Expected-to-fail tcl test cases that were not reported as failed: [info-15.4](..)

Tests in error:
  testIo(tcl.lang.cmd.MiscCmdTest): Exception while running tcltest(..)

Tests run: 125, Failures: 5, Errors: 1, Skipped: 0
```
I'd help if i knew where to start but i'm a total 0 in java :)

**Comment by Dufgui** [comment]
Hello, i continue to work on this when I have time to spend on i ;o)
In fact, i am working on create integration to intellij and eclipse actually.
After i want to manage tcl namespace.
After I will fix test and start to have something usable.

**Comment by crazycodr** [comment]
Ok cool, i think i'll fork it, develop it a little to fix what i can and submit PRs once i'm happy with what i have
